version: '3.8'

services: 
  mysql: 
    container_name: mysql8_Node
    image: mysql:8.0.20
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: bd_nest